# Generated by Django 4.2.1 on 2023-05-30 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_auto_20230530_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 20, 30, 35, 38517)),
        ),
    ]
